#name: Java GitHub CI
#
#run-name: ${{ github.actor }} pushed a new code
#
#permissions: write-all
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    name: Build application
#    uses: ./.github/workflows/build_job.yml
#
#  review:
#    name: Code review
#    uses: ./.github/workflows/review_job.yml