name: AI Code Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: AI Code Review
        uses: lfsevergnini/ai-codereviewer@chore/add-model-version-parameter
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-3.5-turbo"
          exclude: "**/*.json, **/*.md, **/*.yml, **/*.yaml, **/*.js, **/*.html"